import 'package:baby_name_app/models/baby_name_models.dart';

class AppControllers {
  static int selectedBaby = 1;
  static String selectedReligion = "Christianity";

  static List<BabyNameModel> favouriteList = [];

  static List<BabyNameModel> babyNameList = [
    // Christianity - Boys
    BabyNameModel(id: 1, babyType: 1, name: "Ethan", nameMeaning: "Strong, Firm", religion: "Christianity"),
    BabyNameModel(id: 2, babyType: 1, name: "Lucas", nameMeaning: "Light; Bringer of light", religion: "Christianity"),
    BabyNameModel(id: 3, babyType: 1, name: "Samuel", nameMeaning: "God has heard", religion: "Christianity"),
    BabyNameModel(id: 4, babyType: 1, name: "Liam", nameMeaning: "Strong-willed warrior", religion: "Christianity"),
    BabyNameModel(id: 5, babyType: 1, name: "Noah", nameMeaning: "Rest; Comfort", religion: "Christianity"),
    BabyNameModel(id: 6, babyType: 1, name: "Jacob", nameMeaning: "Supplanter", religion: "Christianity"),
    BabyNameModel(id: 7, babyType: 1, name: "Michael", nameMeaning: "Who is like God", religion: "Christianity"),
    BabyNameModel(id: 8, babyType: 1, name: "Daniel", nameMeaning: "God is my judge", religion: "Christianity"),
    BabyNameModel(id: 9, babyType: 1, name: "Matthew", nameMeaning: "Gift of God", religion: "Christianity"),
    BabyNameModel(id: 10, babyType: 1, name: "James", nameMeaning: "Supplanter", religion: "Christianity"),
    BabyNameModel(id: 11, babyType: 1, name: "Benjamin", nameMeaning: "Son of the right hand", religion: "Christianity"),
    BabyNameModel(id: 12, babyType: 1, name: "David", nameMeaning: "Beloved", religion: "Christianity"),
    BabyNameModel(id: 13, babyType: 1, name: "Joseph", nameMeaning: "He will add", religion: "Christianity"),
    BabyNameModel(id: 14, babyType: 1, name: "Andrew", nameMeaning: "Manly", religion: "Christianity"),
    BabyNameModel(id: 15, babyType: 1, name: "Christopher", nameMeaning: "Bearer of Christ", religion: "Christianity"),

    // Christianity - Girls
    BabyNameModel(id: 16, babyType: 2, name: "Sophia", nameMeaning: "Wisdom", religion: "Christianity"),
    BabyNameModel(id: 17, babyType: 2, name: "Emma", nameMeaning: "Universal", religion: "Christianity"),
    BabyNameModel(id: 18, babyType: 2, name: "Olivia", nameMeaning: "Olive tree", religion: "Christianity"),
    BabyNameModel(id: 19, babyType: 2, name: "Ava", nameMeaning: "Bird", religion: "Christianity"),
    BabyNameModel(id: 20, babyType: 2, name: "Isabella", nameMeaning: "God is my oath", religion: "Christianity"),
    BabyNameModel(id: 21, babyType: 2, name: "Mia", nameMeaning: "Mine", religion: "Christianity"),
    BabyNameModel(id: 22, babyType: 2, name: "Amelia", nameMeaning: "Work", religion: "Christianity"),
    BabyNameModel(id: 23, babyType: 2, name: "Harper", nameMeaning: "Harp player", religion: "Christianity"),
    BabyNameModel(id: 24, babyType: 2, name: "Evelyn", nameMeaning: "Desired", religion: "Christianity"),
    BabyNameModel(id: 25, babyType: 2, name: "Abigail", nameMeaning: "Father's joy", religion: "Christianity"),
    BabyNameModel(id: 26, babyType: 2, name: "Emily", nameMeaning: "Rival", religion: "Christianity"),
    BabyNameModel(id: 27, babyType: 2, name: "Elizabeth", nameMeaning: "God is my oath", religion: "Christianity"),
    BabyNameModel(id: 28, babyType: 2, name: "Mila", nameMeaning: "Gracious", religion: "Christianity"),
    BabyNameModel(id: 29, babyType: 2, name: "Ella", nameMeaning: "Fairy maiden", religion: "Christianity"),
    BabyNameModel(id: 30, babyType: 2, name: "Avery", nameMeaning: "Ruler of the elves", religion: "Christianity"),

    // Christianity - Twins
    BabyNameModel(id: 31, babyType: 3, name: "Evan", name2: "Ethan", nameMeaning: "Young warrior", nameMeaning2: "Strong, Firm", religion: "Christianity", twinType: "boys"),
    BabyNameModel(id: 32, babyType: 3, name: "Liam", name2: "Leo", nameMeaning: "Strong-willed warrior", nameMeaning2: "Lion", religion: "Christianity", twinType: "boys"),
    BabyNameModel(id: 33, babyType: 3, name: "Mia", name2: "Maria", nameMeaning: "Mine", nameMeaning2: "Wished for child", religion: "Christianity", twinType: "girls"),
    BabyNameModel(id: 34, babyType: 3, name: "Ella", name2: "Emma", nameMeaning: "Fairy maiden", nameMeaning2: "Universal", religion: "Christianity", twinType: "girls"),
    BabyNameModel(id: 35, babyType: 3, name: "Sophia", name2: "Sadie", nameMeaning: "Wisdom", nameMeaning2: "Princess", religion: "Christianity", twinType: "girls"),
    BabyNameModel(id: 36, babyType: 3, name: "Jacob", name2: "James", nameMeaning: "Supplanter", nameMeaning2: "Supplanter", religion: "Christianity", twinType: "boys"),
    BabyNameModel(id: 37, babyType: 3, name: "Lily", name2: "Lana", nameMeaning: "Lily flower", nameMeaning2: "Light", religion: "Christianity", twinType: "girls"),
    BabyNameModel(id: 38, babyType: 3, name: "Aidan", name2: "Asher", nameMeaning: "Little fire", nameMeaning2: "Happy", religion: "Christianity", twinType: "boys"),
    BabyNameModel(id: 39, babyType: 3, name: "Amir", name2: "Ayaan", nameMeaning: "Prince", nameMeaning2: "Blessed", religion: "Christianity", twinType: "boys"),
    BabyNameModel(id: 40, babyType: 3, name: "Noah", name2: "Nadia", nameMeaning: "Rest", nameMeaning2: "Hope", religion: "Christianity", twinType: "fraternal"),
    BabyNameModel(id: 41, babyType: 3, name: "Isaac", name2: "Ibrahim", nameMeaning: "Laughter", nameMeaning2: "Father of many", religion: "Christianity", twinType: "boys"),
    BabyNameModel(id: 42, babyType: 3, name: "Zara", name2: "Zane", nameMeaning: "Princess", nameMeaning2: "Gift of God", religion: "Christianity", twinType: "fraternal"),
    BabyNameModel(id: 43, babyType: 3, name: "Maya", name2: "Mariam", nameMeaning: "Illusion", nameMeaning2: "Beloved", religion: "Christianity", twinType: "girls"),
    BabyNameModel(id: 44, babyType: 3, name: "Aditya", name2: "Anuj", nameMeaning: "Sun God", nameMeaning2: "Younger brother", religion: "Christianity", twinType: "boys"),
    BabyNameModel(id: 45, babyType: 3, name: "Rina", name2: "Rita", nameMeaning: "Peaceful", nameMeaning2: "Pearl", religion: "Christianity", twinType: "girls"),

    // Hinduism - Boys
    BabyNameModel(id: 46, babyType: 1, name: "Rajinikanth", nameMeaning: "Super Star", religion: "Hinduism"),
    BabyNameModel(id: 47, babyType: 1, name: "Ravi", nameMeaning: "Sun; King", religion: "Hinduism"),
    BabyNameModel(id: 48, babyType: 1, name: "Aryan", nameMeaning: "Noble; Pure", religion: "Hinduism"),
    BabyNameModel(id: 49, babyType: 1, name: "Arjun", nameMeaning: "Bright; White", religion: "Hinduism"),
    BabyNameModel(id: 50, babyType: 1, name: "Kiran", nameMeaning: "Ray of light", religion: "Hinduism"),
    BabyNameModel(id: 51, babyType: 1, name: "Ananya", nameMeaning: "Unique", religion: "Hinduism"),
    BabyNameModel(id: 52, babyType: 1, name: "Aditya", nameMeaning: "Sun God", religion: "Hinduism"),
    BabyNameModel(id: 53, babyType: 1, name: "Raj", nameMeaning: "King", religion: "Hinduism"),
    BabyNameModel(id: 54, babyType: 1, name: "Vivaan", nameMeaning: "Full of life", religion: "Hinduism"),
    BabyNameModel(id: 55, babyType: 1, name: "Aarav", nameMeaning: "Peaceful", religion: "Hinduism"),
    BabyNameModel(id: 56, babyType: 1, name: "Rohan", nameMeaning: "Ascending", religion: "Hinduism"),
    BabyNameModel(id: 57, babyType: 1, name: "Siddharth", nameMeaning: "Achieved", religion: "Hinduism"),
    BabyNameModel(id: 58, babyType: 1, name: "Vihaan", nameMeaning: "Dawn", religion: "Hinduism"),
    BabyNameModel(id: 59, babyType: 1, name: "Yash", nameMeaning: "Fame", religion: "Hinduism"),
    BabyNameModel(id: 60, babyType: 1, name: "Dhruv", nameMeaning: "Pole star", religion: "Hinduism"),

    // Hinduism - Girls
    BabyNameModel(id: 61, babyType: 2, name: "Lila", nameMeaning: "Night; Beauty", religion: "Hinduism"),
    BabyNameModel(id: 62, babyType: 2, name: "Kavya", nameMeaning: "Poetry; Creativity", religion: "Hinduism"),
    BabyNameModel(id: 63, babyType: 2, name: "Ananya", nameMeaning: "Unique", religion: "Hinduism"),
    BabyNameModel(id: 64, babyType: 2, name: "Alisha", nameMeaning: "Protected by God", religion: "Hinduism"),
    BabyNameModel(id: 65, babyType: 2, name: "Maya", nameMeaning: "Illusion", religion: "Hinduism"),
    BabyNameModel(id: 66, babyType: 2, name: "Rina", nameMeaning: "Peaceful", religion: "Hinduism"),
    BabyNameModel(id: 67, babyType: 2, name: "Rita", nameMeaning: "Pearl", religion: "Hinduism"),
    BabyNameModel(id: 68, babyType: 2, name: "Saanvi", nameMeaning: "Goddess Lakshmi", religion: "Hinduism"),
    BabyNameModel(id: 69, babyType: 2, name: "Anika", nameMeaning: "Grace", religion: "Hinduism"),
    BabyNameModel(id: 70, babyType: 2, name: "Diya", nameMeaning: "Lamp", religion: "Hinduism"),
    BabyNameModel(id: 71, babyType: 2, name: "Ishani", nameMeaning: "Goddess Durga", religion: "Hinduism"),
    BabyNameModel(id: 72, babyType: 2, name: "Kiara", nameMeaning: "Bright", religion: "Hinduism"),
    BabyNameModel(id: 73, babyType: 2, name: "Mira", nameMeaning: "Prosperous", religion: "Hinduism"),
    BabyNameModel(id: 74, babyType: 2, name: "Neha", nameMeaning: "Rain", religion: "Hinduism"),
    BabyNameModel(id: 75, babyType: 2, name: "Priya", nameMeaning: "Beloved", religion: "Hinduism"),

    // Hinduism - Twins
    BabyNameModel(id: 76, babyType: 3, name: "Aryan", name2: "Arjun", nameMeaning: "Noble; Pure", nameMeaning2: "Bright; White", religion: "Hinduism", twinType: "boys"),
    BabyNameModel(id: 77, babyType: 3, name: "Kiran", name2: "Kavya", nameMeaning: "Ray of light", nameMeaning2: "Poetry; Creativity", religion: "Hinduism", twinType: "fraternal"),
    BabyNameModel(id: 78, babyType: 3, name: "Aditya", name2: "Anuj", nameMeaning: "Sun God", nameMeaning2: "Younger brother", religion: "Hinduism", twinType: "boys"),
    BabyNameModel(id: 79, babyType: 3, name: "Rina", name2: "Rita", nameMeaning: "Peaceful", nameMeaning2: "Pearl", religion: "Hinduism", twinType: "girls"),
    BabyNameModel(id: 80, babyType: 3, name: "Vivaan", name2: "Vihaan", nameMeaning: "Full of life", nameMeaning2: "Dawn", religion: "Hinduism", twinType: "boys"),
    BabyNameModel(id: 81, babyType: 3, name: "Saanvi", name2: "Sia", nameMeaning: "Goddess Lakshmi", nameMeaning2: "Goddess Sita", religion: "Hinduism", twinType: "girls"),
    BabyNameModel(id: 82, babyType: 3, name: "Anika", name2: "Anaya", nameMeaning: "Grace", nameMeaning2: "Caring", religion: "Hinduism", twinType: "girls"),
    BabyNameModel(id: 83, babyType: 3, name: "Diya", name2: "Disha", nameMeaning: "Lamp", nameMeaning2: "Direction", religion: "Hinduism", twinType: "girls"),
    BabyNameModel(id: 84, babyType: 3, name: "Ishani", name2: "Ishita", nameMeaning: "Goddess Durga", nameMeaning2: "Desire", religion: "Hinduism", twinType: "girls"),
    BabyNameModel(id: 85, babyType: 3, name: "Kiara", name2: "Kriti", nameMeaning: "Bright", nameMeaning2: "Creation", religion: "Hinduism", twinType: "girls"),
    BabyNameModel(id: 86, babyType: 3, name: "Mira", name2: "Minal", nameMeaning: "Prosperous", nameMeaning2: "Fish", religion: "Hinduism", twinType: "girls"),
    BabyNameModel(id: 87, babyType: 3, name: "Neha", name2: "Nisha", nameMeaning: "Rain", nameMeaning2: "Night", religion: "Hinduism", twinType: "girls"),
    BabyNameModel(id: 88, babyType: 3, name: "Priya", name2: "Pooja", nameMeaning: "Beloved", nameMeaning2: "Worship", religion: "Hinduism", twinType: "girls"),
    BabyNameModel(id: 89, babyType: 3, name: "Rohan", name2: "Rohit", nameMeaning: "Ascending", nameMeaning2: "Red", religion: "Hinduism", twinType: "boys"),
    BabyNameModel(id: 90, babyType: 3, name: "Siddharth", name2: "Surya", nameMeaning: "Achieved", nameMeaning2: "Sun", religion: "Hinduism", twinType: "boys"),

    // Islam - Boys
    BabyNameModel(id: 91, babyType: 1, name: "Ayaan", nameMeaning: "Blessed", religion: "Islam"),
    BabyNameModel(id: 92, babyType: 1, name: "Amir", nameMeaning: "Prince", religion: "Islam"),
    BabyNameModel(id: 93, babyType: 1, name: "Imran", nameMeaning: "Prosperity", religion: "Islam"),
    BabyNameModel(id: 94, babyType: 1, name: "Zain", nameMeaning: "Grace", religion: "Islam"),
    BabyNameModel(id: 95, babyType: 1, name: "Ali", nameMeaning: "Exalted", religion: "Islam"),
    BabyNameModel(id: 96, babyType: 1, name: "Omar", nameMeaning: "Long-lived", religion: "Islam"),
    BabyNameModel(id: 97, babyType: 1, name: "Yusuf", nameMeaning: "God increases", religion: "Islam"),
    BabyNameModel(id: 98, babyType: 1, name: "Ibrahim", nameMeaning: "Father of many", religion: "Islam"),
    BabyNameModel(id: 99, babyType: 1, name: "Hamza", nameMeaning: "Lion", religion: "Islam"),
    BabyNameModel(id: 100, babyType: 1, name: "Tariq", nameMeaning: "Morning star", religion: "Islam"),
    BabyNameModel(id: 101, babyType: 1, name: "Khalid", nameMeaning: "Eternal", religion: "Islam"),
    BabyNameModel(id: 102, babyType: 1, name: "Rashid", nameMeaning: "Rightly guided", religion: "Islam"),
    BabyNameModel(id: 103, babyType: 1, name: "Samir", nameMeaning: "Companion in evening talk", religion: "Islam"),
    BabyNameModel(id: 104, babyType: 1, name: "Farhan", nameMeaning: "Happy", religion: "Islam"),
    BabyNameModel(id: 105, babyType: 1, name: "Asad", nameMeaning: "Lion", religion: "Islam"),

    // Islam - Girls
    BabyNameModel(id: 106, babyType: 2, name: "Aaliyah", nameMeaning: "Exalted; High-ranking", religion: "Islam"),
    BabyNameModel(id: 107, babyType: 2, name: "Amira", nameMeaning: "Princess; Leader", religion: "Islam"),
    BabyNameModel(id: 108, babyType: 2, name: "Zara", nameMeaning: "Princess; Flower", religion: "Islam"),
    BabyNameModel(id: 109, babyType: 2, name: "Fatima", nameMeaning: "Captivating", religion: "Islam"),
    BabyNameModel(id: 110, babyType: 2, name: "Aisha", nameMeaning: "Living", religion: "Islam"),
    BabyNameModel(id: 111, babyType: 2, name: "Layla", nameMeaning: "Night", religion: "Islam"),
    BabyNameModel(id: 112, babyType: 2, name: "Safiya", nameMeaning: "Pure", religion: "Islam"),
    BabyNameModel(id: 113, babyType: 2, name: "Nadia", nameMeaning: "Hope", religion: "Islam"),
    BabyNameModel(id: 114, babyType: 2, name: "Yasmin", nameMeaning: "Jasmine flower", religion: "Islam"),
    BabyNameModel(id: 115, babyType: 2, name: "Hana", nameMeaning: "Happiness", religion: "Islam"),
    BabyNameModel(id: 116, babyType: 2, name: "Leila", nameMeaning: "Dark beauty", religion: "Islam"),
    BabyNameModel(id: 117, babyType: 2, name: "Mariam", nameMeaning: "Beloved", religion: "Islam"),
    BabyNameModel(id: 118, babyType: 2, name: "Zahra", nameMeaning: "Flower", religion: "Islam"),
    BabyNameModel(id: 119, babyType: 2, name: "Samira", nameMeaning: "Companion in evening talk", religion: "Islam"),
    BabyNameModel(id: 120, babyType: 2, name: "Noor", nameMeaning: "Light", religion: "Islam"),

    // Islam - Twins
    BabyNameModel(id: 121, babyType: 3, name: "Amir", name2: "Ayaan", nameMeaning: "Prince", nameMeaning2: "Blessed", religion: "Islam", twinType: "boys"),
    BabyNameModel(id: 122, babyType: 3, name: "Zain", name2: "Zara", nameMeaning: "Grace", nameMeaning2: "Princess", religion: "Islam", twinType: "fraternal"),
    BabyNameModel(id: 123, babyType: 3, name: "Ali", name2: "Aisha", nameMeaning: "Exalted", nameMeaning2: "Living", religion: "Islam", twinType: "fraternal"),
    BabyNameModel(id: 124, babyType: 3, name: "Omar", name2: "Layla", nameMeaning: "Long-lived", nameMeaning2: "Night", religion: "Islam", twinType: "fraternal"),
    BabyNameModel(id: 125, babyType: 3, name: "Yusuf", name2: "Yasmin", nameMeaning: "God increases", nameMeaning2: "Jasmine flower", religion: "Islam", twinType: "fraternal"),
    BabyNameModel(id: 126, babyType: 3, name: "Ibrahim", name2: "Hana", nameMeaning: "Father of many", nameMeaning2: "Happiness", religion: "Islam", twinType: "fraternal"),
    BabyNameModel(id: 127, babyType: 3, name: "Hamza", name2: "Hana", nameMeaning: "Lion", nameMeaning2: "Happiness", religion: "Islam", twinType: "fraternal"),
    BabyNameModel(id: 128, babyType: 3, name: "Tariq", name2: "Tahira", nameMeaning: "Morning star", nameMeaning2: "Pure", religion: "Islam", twinType: "fraternal"),
    BabyNameModel(id: 129, babyType: 3, name: "Khalid", name2: "Khadija", nameMeaning: "Eternal", nameMeaning2: "Premature child", religion: "Islam", twinType: "fraternal"),
    BabyNameModel(id: 130, babyType: 3, name: "Rashid", name2: "Rania", nameMeaning: "Rightly guided", nameMeaning2: "Queen", religion: "Islam", twinType: "fraternal"),
    BabyNameModel(id: 131, babyType: 3, name: "Samir", name2: "Samira", nameMeaning: "Companion in evening talk", nameMeaning2: "Companion in evening talk", religion: "Islam", twinType: "fraternal"),
    BabyNameModel(id: 132, babyType: 3, name: "Farhan", name2: "Farah", nameMeaning: "Happy", nameMeaning2: "Joy", religion: "Islam", twinType: "fraternal"),
    BabyNameModel(id: 133, babyType: 3, name: "Asad", name2: "Amina", nameMeaning: "Lion", nameMeaning2: "Trustworthy", religion: "Islam", twinType: "fraternal"),
    BabyNameModel(id: 134, babyType: 3, name: "Zahid", name2: "Zahra", nameMeaning: "Pious", nameMeaning2: "Flower", religion: "Islam", twinType: "fraternal"),
    BabyNameModel(id: 135, babyType: 3, name: "Nadir", name2: "Nadia", nameMeaning: "Rare", nameMeaning2: "Hope", religion: "Islam", twinType: "fraternal"),

    // Judaism - Boys
    BabyNameModel(id: 136, babyType: 1, name: "Noah", nameMeaning: "Rest; Comfort", religion: "Judaism"),
    BabyNameModel(id: 137, babyType: 1, name: "Jacob", nameMeaning: "Supplanter", religion: "Judaism"),
    BabyNameModel(id: 138, babyType: 1, name: "Samuel", nameMeaning: "God has heard", religion: "Judaism"),
    BabyNameModel(id: 139, babyType: 1, name: "David", nameMeaning: "Beloved", religion: "Judaism"),
    BabyNameModel(id: 140, babyType: 1, name: "Benjamin", nameMeaning: "Son of the right hand", religion: "Judaism"),
    BabyNameModel(id: 141, babyType: 1, name: "Isaac", nameMeaning: "Laughter", religion: "Judaism"),
    BabyNameModel(id: 142, babyType: 1, name: "Aaron", nameMeaning: "High mountain", religion: "Judaism"),
    BabyNameModel(id: 143, babyType: 1, name: "Ethan", nameMeaning: "Strong, Firm", religion: "Judaism"),
    BabyNameModel(id: 144, babyType: 1, name: "Daniel", nameMeaning: "God is my judge", religion: "Judaism"),
    BabyNameModel(id: 145, babyType: 1, name: "Joseph", nameMeaning: "He will add", religion: "Judaism"),
    BabyNameModel(id: 146, babyType: 1, name: "Joshua", nameMeaning: "God is salvation", religion: "Judaism"),
    BabyNameModel(id: 147, babyType: 1, name: "Michael", nameMeaning: "Who is like God", religion: "Judaism"),
    BabyNameModel(id: 148, babyType: 1, name: "Adam", nameMeaning: "Man", religion: "Judaism"),
    BabyNameModel(id: 149, babyType: 1, name: "Nathan", nameMeaning: "He gave", religion: "Judaism"),
    BabyNameModel(id: 150, babyType: 1, name: "Elijah", nameMeaning: "My God is Yahweh", religion: "Judaism"),

    // Judaism - Girls
    BabyNameModel(id: 151, babyType: 2, name: "Leah", nameMeaning: "Weary", religion: "Judaism"),
    BabyNameModel(id: 152, babyType: 2, name: "Rachel", nameMeaning: "Ewe", religion: "Judaism"),
    BabyNameModel(id: 153, babyType: 2, name: "Sarah", nameMeaning: "Princess", religion: "Judaism"),
    BabyNameModel(id: 154, babyType: 2, name: "Rebecca", nameMeaning: "To bind", religion: "Judaism"),
    BabyNameModel(id: 155, babyType: 2, name: "Miriam", nameMeaning: "Rebellious", religion: "Judaism"),
    BabyNameModel(id: 156, babyType: 2, name: "Esther", nameMeaning: "Star", religion: "Judaism"),
    BabyNameModel(id: 157, babyType: 2, name: "Hannah", nameMeaning: "Grace", religion: "Judaism"),
    BabyNameModel(id: 158, babyType: 2, name: "Abigail", nameMeaning: "Father's joy", religion: "Judaism"),
    BabyNameModel(id: 159, babyType: 2, name: "Naomi", nameMeaning: "Pleasantness", religion: "Judaism"),
    BabyNameModel(id: 160, babyType: 2, name: "Ruth", nameMeaning: "Friend", religion: "Judaism"),
    BabyNameModel(id: 161, babyType: 2, name: "Deborah", nameMeaning: "Bee", religion: "Judaism"),
    BabyNameModel(id: 162, babyType: 2, name: "Tamar", nameMeaning: "Palm tree", religion: "Judaism"),
    BabyNameModel(id: 163, babyType: 2, name: "Shira", nameMeaning: "Song", religion: "Judaism"),
    BabyNameModel(id: 164, babyType: 2, name: "Aviva", nameMeaning: "Spring", religion: "Judaism"),
    BabyNameModel(id: 165, babyType: 2, name: "Talia", nameMeaning: "Dew from God", religion: "Judaism"),

    // Judaism - Twins
    BabyNameModel(id: 166, babyType: 3, name: "Noah", name2: "Nadia", nameMeaning: "Rest", nameMeaning2: "Hope", religion: "Judaism", twinType: "fraternal"),
    BabyNameModel(id: 167, babyType: 3, name: "Jacob", name2: "James", nameMeaning: "Supplanter", nameMeaning2: "Supplanter", religion: "Judaism", twinType: "boys"),
    BabyNameModel(id: 168, babyType: 3, name: "Samuel", name2: "Sarah", nameMeaning: "God has heard", nameMeaning2: "Princess", religion: "Judaism", twinType: "fraternal"),
    BabyNameModel(id: 169, babyType: 3, name: "David", name2: "Deborah", nameMeaning: "Beloved", nameMeaning2: "Bee", religion: "Judaism", twinType: "fraternal"),
    BabyNameModel(id: 170, babyType: 3, name: "Benjamin", name2: "Bina", nameMeaning: "Son of the right hand", nameMeaning2: "Understanding", religion: "Judaism", twinType: "fraternal"),
    BabyNameModel(id: 171, babyType: 3, name: "Isaac", name2: "Ishmael", nameMeaning: "Laughter", nameMeaning2: "God will hear", religion: "Judaism", twinType: "boys"),
    BabyNameModel(id: 172, babyType: 3, name: "Aaron", name2: "Aviva", nameMeaning: "High mountain", nameMeaning2: "Spring", religion: "Judaism", twinType: "fraternal"),
    BabyNameModel(id: 173, babyType: 3, name: "Ethan", name2: "Eliana", nameMeaning: "Strong, Firm", nameMeaning2: "God has answered", religion: "Judaism", twinType: "fraternal"),
    BabyNameModel(id: 174, babyType: 3, name: "Daniel", name2: "Dina", nameMeaning: "God is my judge", nameMeaning2: "Judged", religion: "Judaism", twinType: "fraternal"),
    BabyNameModel(id: 175, babyType: 3, name: "Joseph", name2: "Jael", nameMeaning: "He will add", nameMeaning2: "Mountain goat", religion: "Judaism", twinType: "fraternal"),
    BabyNameModel(id: 176, babyType: 3, name: "Joshua", name2: "Jasmine", nameMeaning: "God is salvation", nameMeaning2: "Jasmine flower", religion: "Judaism", twinType: "fraternal"),
    BabyNameModel(id: 177, babyType: 3, name: "Michael", name2: "Miriam", nameMeaning: "Who is like God", nameMeaning2: "Rebellious", religion: "Judaism", twinType: "fraternal"),
    BabyNameModel(id: 178, babyType: 3, name: "Adam", name2: "Adina", nameMeaning: "Man", nameMeaning2: "Delicate", religion: "Judaism", twinType: "fraternal"),
    BabyNameModel(id: 179, babyType: 3, name: "Nathan", name2: "Nava", nameMeaning: "He gave", nameMeaning2: "Beautiful", religion: "Judaism", twinType: "fraternal"),
    BabyNameModel(id: 180, babyType: 3, name: "Elijah", name2: "Eliana", nameMeaning: "My God is Yahweh", nameMeaning2: "God has answered", religion: "Judaism", twinType: "fraternal"),

    // Buddhism - Boys
    BabyNameModel(id: 181, babyType: 1, name: "Liam", nameMeaning: "Strong-willed warrior", religion: "Buddhism"),
    BabyNameModel(id: 182, babyType: 1, name: "Noah", nameMeaning: "Rest; Comfort", religion: "Buddhism"),
    BabyNameModel(id: 183, babyType: 1, name: "Aiden", nameMeaning: "Little fire", religion: "Buddhism"),
    BabyNameModel(id: 184, babyType: 1, name: "Leo", nameMeaning: "Lion", religion: "Buddhism"),
    BabyNameModel(id: 185, babyType: 1, name: "Ethan", nameMeaning: "Strong, Firm", religion: "Buddhism"),
    BabyNameModel(id: 186, babyType: 1, name: "Lucas", nameMeaning: "Light; Bringer of light", religion: "Buddhism"),
    BabyNameModel(id: 187, babyType: 1, name: "Mason", nameMeaning: "Stone worker", religion: "Buddhism"),
    BabyNameModel(id: 188, babyType: 1, name: "Logan", nameMeaning: "Little hollow", religion: "Buddhism"),
    BabyNameModel(id: 189, babyType: 1, name: "Oliver", nameMeaning: "Olive tree", religion: "Buddhism"),
    BabyNameModel(id: 190, babyType: 1, name: "Caleb", nameMeaning: "Faithful", religion: "Buddhism"),
    BabyNameModel(id: 191, babyType: 1, name: "Ryan", nameMeaning: "Little king", religion: "Buddhism"),
    BabyNameModel(id: 192, babyType: 1, name: "Nathan", nameMeaning: "He gave", religion: "Buddhism"),
    BabyNameModel(id: 193, babyType: 1, name: "Elijah", nameMeaning: "My God is Yahweh", religion: "Buddhism"),
    BabyNameModel(id: 194, babyType: 1, name: "Daniel", nameMeaning: "God is my judge", religion: "Buddhism"),
    BabyNameModel(id: 195, babyType: 1, name: "Samuel", nameMeaning: "God has heard", religion: "Buddhism"),

    // Buddhism - Girls
    BabyNameModel(id: 196, babyType: 2, name: "Mia", nameMeaning: "Mine", religion: "Buddhism"),
    BabyNameModel(id: 197, babyType: 2, name: "Emma", nameMeaning: "Universal", religion: "Buddhism"),
    BabyNameModel(id: 198, babyType: 2, name: "Olivia", nameMeaning: "Olive tree", religion: "Buddhism"),
    BabyNameModel(id: 199, babyType: 2, name: "Ava", nameMeaning: "Bird", religion: "Buddhism"),
    BabyNameModel(id: 200, babyType: 2, name: "Sophia", nameMeaning: "Wisdom", religion: "Buddhism"),
    BabyNameModel(id: 201, babyType: 2, name: "Isabella", nameMeaning: "God is my oath", religion: "Buddhism"),
    BabyNameModel(id: 202, babyType: 2, name: "Amelia", nameMeaning: "Work", religion: "Buddhism"),
    BabyNameModel(id: 203, babyType: 2, name: "Harper", nameMeaning: "Harp player", religion: "Buddhism"),
    BabyNameModel(id: 204, babyType: 2, name: "Evelyn", nameMeaning: "Desired", religion: "Buddhism"),
    BabyNameModel(id: 205, babyType: 2, name: "Abigail", nameMeaning: "Father's joy", religion: "Buddhism"),
    BabyNameModel(id: 206, babyType: 2, name: "Emily", nameMeaning: "Rival", religion: "Buddhism"),
    BabyNameModel(id: 207, babyType: 2, name: "Elizabeth", nameMeaning: "God is my oath", religion: "Buddhism"),
    BabyNameModel(id: 208, babyType: 2, name: "Mila", nameMeaning: "Gracious", religion: "Buddhism"),
    BabyNameModel(id: 209, babyType: 2, name: "Ella", nameMeaning: "Fairy maiden", religion: "Buddhism"),
    BabyNameModel(id: 210, babyType: 2, name: "Avery", nameMeaning: "Ruler of the elves", religion: "Buddhism"),

    // Buddhism - Twins
    BabyNameModel(id: 211, babyType: 3, name: "Liam", name2: "Leo", nameMeaning: "Strong-willed warrior", nameMeaning2: "Lion", religion: "Buddhism", twinType: "boys"),
    BabyNameModel(id: 212, babyType: 3, name: "Noah", name2: "Nadia", nameMeaning: "Rest", nameMeaning2: "Hope", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 213, babyType: 3, name: "Aiden", name2: "Ava", nameMeaning: "Little fire", nameMeaning2: "Bird", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 214, babyType: 3, name: "Ethan", name2: "Emma", nameMeaning: "Strong, Firm", nameMeaning2: "Universal", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 215, babyType: 3, name: "Lucas", name2: "Lily", nameMeaning: "Light; Bringer of light", nameMeaning2: "Lily flower", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 216, babyType: 3, name: "Mason", name2: "Mia", nameMeaning: "Stone worker", nameMeaning2: "Mine", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 217, babyType: 3, name: "Logan", name2: "Luna", nameMeaning: "Little hollow", nameMeaning2: "Moon", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 218, babyType: 3, name: "Oliver", name2: "Olivia", nameMeaning: "Olive tree", nameMeaning2: "Olive tree", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 219, babyType: 3, name: "Caleb", name2: "Chloe", nameMeaning: "Faithful", nameMeaning2: "Blooming", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 220, babyType: 3, name: "Ryan", name2: "Riley", nameMeaning: "Little king", nameMeaning2: "Courageous", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 221, babyType: 3, name: "Nathan", name2: "Natalie", nameMeaning: "He gave", nameMeaning2: "Christmas Day", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 222, babyType: 3, name: "Elijah", name2: "Eliana", nameMeaning: "My God is Yahweh", nameMeaning2: "God has answered", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 223, babyType: 3, name: "Daniel", name2: "Daisy", nameMeaning: "God is my judge", nameMeaning2: "Day's eye", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 224, babyType: 3, name: "Samuel", name2: "Sophia", nameMeaning: "God has heard", nameMeaning2: "Wisdom", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 225, babyType: 3, name: "Evan", name2: "Evelyn", nameMeaning: "Young warrior", nameMeaning2: "Desired", religion: "Buddhism", twinType: "fraternal"),

    // Sikhism - Boys
    BabyNameModel(id: 226, babyType: 1, name: "Aman", nameMeaning: "Peace", religion: "Sikhism"),
    BabyNameModel(id: 227, babyType: 1, name: "Arjun", nameMeaning: "Bright; White", religion: "Sikhism"),
    BabyNameModel(id: 228, babyType: 1, name: "Gurpreet", nameMeaning: "Love of the Guru", religion: "Sikhism"),
    BabyNameModel(id: 229, babyType: 1, name: "Jaspreet", nameMeaning: "Love of praise", religion: "Sikhism"),
    BabyNameModel(id: 230, babyType: 1, name: "Karan", nameMeaning: "Compassionate", religion: "Sikhism"),
    BabyNameModel(id: 231, babyType: 1, name: "Manpreet", nameMeaning: "Love of the mind", religion: "Sikhism"),
    BabyNameModel(id: 232, babyType: 1, name: "Rohan", nameMeaning: "Ascending", religion: "Sikhism"),
    BabyNameModel(id: 233, babyType: 1, name: "Simran", nameMeaning: "Meditation", religion: "Sikhism"),
    BabyNameModel(id: 234, babyType: 1, name: "Taran", nameMeaning: "Raft", religion: "Sikhism"),
    BabyNameModel(id: 235, babyType: 1, name: "Veer", nameMeaning: "Brave", religion: "Sikhism"),
    BabyNameModel(id: 236, babyType: 1, name: "Yuvraj", nameMeaning: "Prince", religion: "Sikhism"),
    BabyNameModel(id: 237, babyType: 1, name: "Aryan", nameMeaning: "Noble; Pure", religion: "Sikhism"),
    BabyNameModel(id: 238, babyType: 1, name: "Dilpreet", nameMeaning: "Love of the heart", religion: "Sikhism"),
    BabyNameModel(id: 239, babyType: 1, name: "Harpreet", nameMeaning: "Love of God", religion: "Sikhism"),
    BabyNameModel(id: 240, babyType: 1, name: "Jagjit", nameMeaning: "Conqueror of the world", religion: "Sikhism"),

    // Sikhism - Girls
    BabyNameModel(id: 241, babyType: 2, name: "Alisha", nameMeaning: "Protected by God", religion: "Sikhism"),
    BabyNameModel(id: 242, babyType: 2, name: "Amrit", nameMeaning: "Nectar", religion: "Sikhism"),
    BabyNameModel(id: 243, babyType: 2, name: "Gurleen", nameMeaning: "Absorbed in the Guru", religion: "Sikhism"),
    BabyNameModel(id: 244, babyType: 2, name: "Harleen", nameMeaning: "Absorbed in God", religion: "Sikhism"),
    BabyNameModel(id: 245, babyType: 2, name: "Jasleen", nameMeaning: "Absorbed in praise", religion: "Sikhism"),
    BabyNameModel(id: 246, babyType: 2, name: "Kiran", nameMeaning: "Ray of light", religion: "Sikhism"),
    BabyNameModel(id: 247, babyType: 2, name: "Manpreet", nameMeaning: "Love of the mind", religion: "Sikhism"),
    BabyNameModel(id: 248, babyType: 2, name: "Navneet", nameMeaning: "New", religion: "Sikhism"),
    BabyNameModel(id: 249, babyType: 2, name: "Prabhleen", nameMeaning: "Absorbed in God's light", religion: "Sikhism"),
    BabyNameModel(id: 250, babyType: 2, name: "Rajinder", nameMeaning: "King", religion: "Sikhism"),
    BabyNameModel(id: 251, babyType: 2, name: "Simran", nameMeaning: "Meditation", religion: "Sikhism"),
    BabyNameModel(id: 252, babyType: 2, name: "Taran", nameMeaning: "Raft", religion: "Sikhism"),
    BabyNameModel(id: 253, babyType: 2, name: "Veer", nameMeaning: "Brave", religion: "Sikhism"),
    BabyNameModel(id: 254, babyType: 2, name: "Yuvraj", nameMeaning: "Prince", religion: "Sikhism"),
    BabyNameModel(id: 255, babyType: 2, name: "Zora", nameMeaning: "Dawn", religion: "Sikhism"),

    // Sikhism - Twins
    BabyNameModel(id: 256, babyType: 3, name: "Aman", name2: "Amrit", nameMeaning: "Peace", nameMeaning2: "Nectar", religion: "Sikhism", twinType: "fraternal"),
    BabyNameModel(id: 257, babyType: 3, name: "Arjun", name2: "Alisha", nameMeaning: "Bright; White", nameMeaning2: "Protected by God", religion: "Sikhism", twinType: "fraternal"),
    BabyNameModel(id: 258, babyType: 3, name: "Gurpreet", name2: "Gurleen", nameMeaning: "Love of the Guru", nameMeaning2: "Absorbed in the Guru", religion: "Sikhism", twinType: "fraternal"),
    BabyNameModel(id: 259, babyType: 3, name: "Jaspreet", name2: "Jasleen", nameMeaning: "Love of praise", nameMeaning2: "Absorbed in praise", religion: "Sikhism", twinType: "fraternal"),
    BabyNameModel(id: 260, babyType: 3, name: "Karan", name2: "Kiran", nameMeaning: "Compassionate", nameMeaning2: "Ray of light", religion: "Sikhism", twinType: "fraternal"),
    BabyNameModel(id: 261, babyType: 3, name: "Manpreet", name2: "Manpreet", nameMeaning: "Love of the mind", nameMeaning2: "Love of the mind", religion: "Sikhism", twinType: "fraternal"),
    BabyNameModel(id: 262, babyType: 3, name: "Rohan", name2: "Rajinder", nameMeaning: "Ascending", nameMeaning2: "King", religion: "Sikhism", twinType: "fraternal"),
    BabyNameModel(id: 263, babyType: 3, name: "Simran", name2: "Simran", nameMeaning: "Meditation", nameMeaning2: "Meditation", religion: "Sikhism", twinType: "fraternal"),
    BabyNameModel(id: 264, babyType: 3, name: "Taran", name2: "Taran", nameMeaning: "Raft", nameMeaning2: "Raft", religion: "Sikhism", twinType: "fraternal"),
    BabyNameModel(id: 265, babyType: 3, name: "Veer", name2: "Veer", nameMeaning: "Brave", nameMeaning2: "Brave", religion: "Sikhism", twinType: "fraternal"),
    BabyNameModel(id: 266, babyType: 3, name: "Yuvraj", name2: "Yuvraj", nameMeaning: "Prince", nameMeaning2: "Prince", religion: "Sikhism", twinType: "fraternal"),
    BabyNameModel(id: 267, babyType: 3, name: "Aryan", name2: "Alisha", nameMeaning: "Noble; Pure", nameMeaning2: "Protected by God", religion: "Sikhism", twinType: "fraternal"),
    BabyNameModel(id: 268, babyType: 3, name: "Dilpreet", name2: "Dilpreet", nameMeaning: "Love of the heart", nameMeaning2: "Love of the heart", religion: "Sikhism", twinType: "fraternal"),
    BabyNameModel(id: 269, babyType: 3, name: "Harpreet", name2: "Harleen", nameMeaning: "Love of God", nameMeaning2: "Absorbed in God", religion: "Sikhism", twinType: "fraternal"),
    BabyNameModel(id: 270, babyType: 3, name: "Jagjit", name2: "Jasleen", nameMeaning: "Conqueror of the world", nameMeaning2: "Absorbed in praise", religion: "Sikhism", twinType: "fraternal"),

    // Jainism - Boys
    BabyNameModel(id: 271, babyType: 1, name: "Aarav", nameMeaning: "Peaceful", religion: "Jainism"),
    BabyNameModel(id: 272, babyType: 1, name: "Aryan", nameMeaning: "Noble; Pure", religion: "Jainism"),
    BabyNameModel(id: 273, babyType: 1, name: "Dhruv", nameMeaning: "Pole star", religion: "Jainism"),
    BabyNameModel(id: 274, babyType: 1, name: "Ishaan", nameMeaning: "Sun", religion: "Jainism"),
    BabyNameModel(id: 275, babyType: 1, name: "Kian", nameMeaning: "Grace of God", religion: "Jainism"),
    BabyNameModel(id: 276, babyType: 1, name: "Mihir", nameMeaning: "Sun", religion: "Jainism"),
    BabyNameModel(id: 277, babyType: 1, name: "Rudra", nameMeaning: "Mighty", religion: "Jainism"),
    BabyNameModel(id: 278, babyType: 1, name: "Siddharth", nameMeaning: "Achieved", religion: "Jainism"),
    BabyNameModel(id: 279, babyType: 1, name: "Vihaan", nameMeaning: "Dawn", religion: "Jainism"),
    BabyNameModel(id: 280, babyType: 1, name: "Yash", nameMeaning: "Fame", religion: "Jainism"),
    BabyNameModel(id: 281, babyType: 1, name: "Aadi", nameMeaning: "First", religion: "Jainism"),
    BabyNameModel(id: 282, babyType: 1, name: "Arnav", nameMeaning: "Ocean", religion: "Jainism"),
    BabyNameModel(id: 283, babyType: 1, name: "Dev", nameMeaning: "God", religion: "Jainism"),
    BabyNameModel(id: 284, babyType: 1, name: "Hrithik", nameMeaning: "From the heart", religion: "Jainism"),
    BabyNameModel(id: 285, babyType: 1, name: "Kabir", nameMeaning: "Great", religion: "Jainism"),

    // Jainism - Girls
    BabyNameModel(id: 286, babyType: 2, name: "Aarohi", nameMeaning: "Ascending", religion: "Jainism"),
    BabyNameModel(id: 287, babyType: 2, name: "Anaya", nameMeaning: "Caring", religion: "Jainism"),
    BabyNameModel(id: 288, babyType: 2, name: "Anika", nameMeaning: "Grace", religion: "Jainism"),
    BabyNameModel(id: 289, babyType: 2, name: "Diya", nameMeaning: "Lamp", religion: "Jainism"),
    BabyNameModel(id: 290, babyType: 2, name: "Ishani", nameMeaning: "Goddess Durga", religion: "Jainism"),
    BabyNameModel(id: 291, babyType: 2, name: "Kiara", nameMeaning: "Bright", religion: "Jainism"),
    BabyNameModel(id: 292, babyType: 2, name: "Mira", nameMeaning: "Prosperous", religion: "Jainism"),
    BabyNameModel(id: 293, babyType: 2, name: "Neha", nameMeaning: "Rain", religion: "Jainism"),
    BabyNameModel(id: 294, babyType: 2, name: "Priya", nameMeaning: "Beloved", religion: "Jainism"),
    BabyNameModel(id: 295, babyType: 2, name: "Riya", nameMeaning: "Singer", religion: "Jainism"),
    BabyNameModel(id: 296, babyType: 2, name: "Saanvi", nameMeaning: "Goddess Lakshmi", religion: "Jainism"),
    BabyNameModel(id: 297, babyType: 2, name: "Tara", nameMeaning: "Star", religion: "Jainism"),
    BabyNameModel(id: 298, babyType: 2, name: "Vanya", nameMeaning: "Gracious", religion: "Jainism"),
    BabyNameModel(id: 299, babyType: 2, name: "Yashvi", nameMeaning: "Famous", religion: "Jainism"),
    BabyNameModel(id: 300, babyType: 2, name: "Zoya", nameMeaning: "Life", religion: "Jainism"),

    // Jainism - Twins
    BabyNameModel(id: 301, babyType: 3, name: "Aarav", name2: "Aarohi", nameMeaning: "Peaceful", nameMeaning2: "Ascending", religion: "Jainism", twinType: "fraternal"),
    BabyNameModel(id: 302, babyType: 3, name: "Aryan", name2: "Anaya", nameMeaning: "Noble; Pure", nameMeaning2: "Caring", religion: "Jainism", twinType: "fraternal"),
    BabyNameModel(id: 303, babyType: 3, name: "Dhruv", name2: "Diya", nameMeaning: "Pole star", nameMeaning2: "Lamp", religion: "Jainism", twinType: "fraternal"),
    BabyNameModel(id: 304, babyType: 3, name: "Ishaan", name2: "Ishani", nameMeaning: "Sun", nameMeaning2: "Goddess Durga", religion: "Jainism", twinType: "fraternal"),
    BabyNameModel(id: 305, babyType: 3, name: "Kian", name2: "Kiara", nameMeaning: "Grace of God", nameMeaning2: "Bright", religion: "Jainism", twinType: "fraternal"),
    BabyNameModel(id: 306, babyType: 3, name: "Mihir", name2: "Mira", nameMeaning: "Sun", nameMeaning2: "Prosperous", religion: "Jainism", twinType: "fraternal"),
    BabyNameModel(id: 307, babyType: 3, name: "Rudra", name2: "Riya", nameMeaning: "Mighty", nameMeaning2: "Singer", religion: "Jainism", twinType: "fraternal"),
    BabyNameModel(id: 308, babyType: 3, name: "Siddharth", name2: "Saanvi", nameMeaning: "Achieved", nameMeaning2: "Goddess Lakshmi", religion: "Jainism", twinType: "fraternal"),
    BabyNameModel(id: 309, babyType: 3, name: "Vihaan", name2: "Vanya", nameMeaning: "Dawn", nameMeaning2: "Gracious", religion: "Jainism", twinType: "fraternal"),
    BabyNameModel(id: 310, babyType: 3, name: "Yash", name2: "Yashvi", nameMeaning: "Fame", nameMeaning2: "Famous", religion: "Jainism", twinType: "fraternal"),
    BabyNameModel(id: 311, babyType: 3, name: "Aadi", name2: "Anika", nameMeaning: "First", nameMeaning2: "Grace", religion: "Jainism", twinType: "fraternal"),
    BabyNameModel(id: 312, babyType: 3, name: "Arnav", name2: "Aarohi", nameMeaning: "Ocean", nameMeaning2: "Ascending", religion: "Jainism", twinType: "fraternal"),
    BabyNameModel(id: 313, babyType: 3, name: "Dev", name2: "Diya", nameMeaning: "God", nameMeaning2: "Lamp", religion: "Jainism", twinType: "fraternal"),
    BabyNameModel(id: 314, babyType: 3, name: "Hrithik", name2: "Hiral", nameMeaning: "From the heart", nameMeaning2: "Diamond", religion: "Jainism", twinType: "fraternal"),
    BabyNameModel(id: 315, babyType: 3, name: "Kabir", name2: "Kiara", nameMeaning: "Great", nameMeaning2: "Bright", religion: "Jainism", twinType: "fraternal"),

    // Zoroastrianism - Boys
    BabyNameModel(id: 316, babyType: 1, name: "Cyrus", nameMeaning: "Sun", religion: "Zoroastrianism"),
    BabyNameModel(id: 317, babyType: 1, name: "Darius", nameMeaning: "Possessing goodness", religion: "Zoroastrianism"),
    BabyNameModel(id: 318, babyType: 1, name: "Farhad", nameMeaning: "Happiness", religion: "Zoroastrianism"),
    BabyNameModel(id: 319, babyType: 1, name: "Kian", nameMeaning: "Grace of God", religion: "Zoroastrianism"),
    BabyNameModel(id: 320, babyType: 1, name: "Rustom", nameMeaning: "Hero", religion: "Zoroastrianism"),
    BabyNameModel(id: 321, babyType: 1, name: "Shapur", nameMeaning: "Son of the king", religion: "Zoroastrianism"),
    BabyNameModel(id: 322, babyType: 1, name: "Zarir", nameMeaning: "Old", religion: "Zoroastrianism"),
    BabyNameModel(id: 323, babyType: 1, name: "Ardeshir", nameMeaning: "Righteous ruler", religion: "Zoroastrianism"),
    BabyNameModel(id: 324, babyType: 1, name: "Bahram", nameMeaning: "Victorious", religion: "Zoroastrianism"),
    BabyNameModel(id: 325, babyType: 1, name: "Jamshed", nameMeaning: "Sun king", religion: "Zoroastrianism"),
    BabyNameModel(id: 326, babyType: 1, name: "Khosrow", nameMeaning: "King", religion: "Zoroastrianism"),
    BabyNameModel(id: 327, babyType: 1, name: "Mehrdad", nameMeaning: "Gift of the sun", religion: "Zoroastrianism"),
    BabyNameModel(id: 328, babyType: 1, name: "Navid", nameMeaning: "Good news", religion: "Zoroastrianism"),
    BabyNameModel(id: 329, babyType: 1, name: "Pirooz", nameMeaning: "Victorious", religion: "Zoroastrianism"),
    BabyNameModel(id: 330, babyType: 1, name: "Roxen", nameMeaning: "Dawn", religion: "Zoroastrianism"),

    // Zoroastrianism - Girls
    BabyNameModel(id: 331, babyType: 2, name: "Anahita", nameMeaning: "Goddess of water", religion: "Zoroastrianism"),
    BabyNameModel(id: 332, babyType: 2, name: "Arezoo", nameMeaning: "Desire", religion: "Zoroastrianism"),
    BabyNameModel(id: 333, babyType: 2, name: "Darya", nameMeaning: "Sea", religion: "Zoroastrianism"),
    BabyNameModel(id: 334, babyType: 2, name: "Farah", nameMeaning: "Joy", religion: "Zoroastrianism"),
    BabyNameModel(id: 335, babyType: 2, name: "Golnar", nameMeaning: "Pomegranate flower", religion: "Zoroastrianism"),
    BabyNameModel(id: 336, babyType: 2, name: "Homa", nameMeaning: "Good omen", religion: "Zoroastrianism"),
    BabyNameModel(id: 337, babyType: 2, name: "Jaleh", nameMeaning: "Dew", religion: "Zoroastrianism"),
    BabyNameModel(id: 338, babyType: 2, name: "Kiana", nameMeaning: "Grace of God", religion: "Zoroastrianism"),
    BabyNameModel(id: 339, babyType: 2, name: "Laleh", nameMeaning: "Tulip", religion: "Zoroastrianism"),
    BabyNameModel(id: 340, babyType: 2, name: "Mehr", nameMeaning: "Sun", religion: "Zoroastrianism"),
    BabyNameModel(id: 341, babyType: 2, name: "Nazanin", nameMeaning: "Sweet", religion: "Zoroastrianism"),
    BabyNameModel(id: 342, babyType: 2, name: "Parisa", nameMeaning: "Like a fairy", religion: "Zoroastrianism"),
    BabyNameModel(id: 343, babyType: 2, name: "Roxana", nameMeaning: "Dawn", religion: "Zoroastrianism"),
    BabyNameModel(id: 344, babyType: 2, name: "Shirin", nameMeaning: "Sweet", religion: "Zoroastrianism"),
    BabyNameModel(id: 345, babyType: 2, name: "Tara", nameMeaning: "Star", religion: "Zoroastrianism"),

    // Zoroastrianism - Twins
    BabyNameModel(id: 346, babyType: 3, name: "Cyrus", name2: "Darya", nameMeaning: "Sun", nameMeaning2: "Sea", religion: "Zoroastrianism", twinType: "fraternal"),
    BabyNameModel(id: 347, babyType: 3, name: "Darius", name2: "Farah", nameMeaning: "Possessing goodness", nameMeaning2: "Joy", religion: "Zoroastrianism", twinType: "fraternal"),
    BabyNameModel(id: 348, babyType: 3, name: "Farhad", name2: "Farah", nameMeaning: "Happiness", nameMeaning2: "Joy", religion: "Zoroastrianism", twinType: "fraternal"),
    BabyNameModel(id: 349, babyType: 3, name: "Kian", name2: "Kiana", nameMeaning: "Grace of God", nameMeaning2: "Grace of God", religion: "Zoroastrianism", twinType: "fraternal"),
    BabyNameModel(id: 350, babyType: 3, name: "Rustom", name2: "Roxana", nameMeaning: "Hero", nameMeaning2: "Dawn", religion: "Zoroastrianism", twinType: "fraternal"),
    BabyNameModel(id: 351, babyType: 3, name: "Shapur", name2: "Shirin", nameMeaning: "Son of the king", nameMeaning2: "Sweet", religion: "Zoroastrianism", twinType: "fraternal"),
    BabyNameModel(id: 352, babyType: 3, name: "Zarir", name2: "Zara", nameMeaning: "Old", nameMeaning2: "Princess", religion: "Zoroastrianism", twinType: "fraternal"),
    BabyNameModel(id: 353, babyType: 3, name: "Ardeshir", name2: "Arezoo", nameMeaning: "Righteous ruler", nameMeaning2: "Desire", religion: "Zoroastrianism", twinType: "fraternal"),
    BabyNameModel(id: 354, babyType: 3, name: "Bahram", name2: "Bahar", nameMeaning: "Victorious", nameMeaning2: "Spring", religion: "Zoroastrianism", twinType: "fraternal"),
    BabyNameModel(id: 355, babyType: 3, name: "Jamshed", name2: "Jaleh", nameMeaning: "Sun king", nameMeaning2: "Dew", religion: "Zoroastrianism", twinType: "fraternal"),
    BabyNameModel(id: 356, babyType: 3, name: "Khosrow", name2: "Kiana", nameMeaning: "King", nameMeaning2: "Grace of God", religion: "Zoroastrianism", twinType: "fraternal"),
    BabyNameModel(id: 357, babyType: 3, name: "Mehrdad", name2: "Mehr", nameMeaning: "Gift of the sun", nameMeaning2: "Sun", religion: "Zoroastrianism", twinType: "fraternal"),
    BabyNameModel(id: 358, babyType: 3, name: "Navid", name2: "Nazanin", nameMeaning: "Good news", nameMeaning2: "Sweet", religion: "Zoroastrianism", twinType: "fraternal"),
    BabyNameModel(id: 359, babyType: 3, name: "Pirooz", name2: "Parisa", nameMeaning: "Victorious", nameMeaning2: "Like a fairy", religion: "Zoroastrianism", twinType: "fraternal"),
    BabyNameModel(id: 360, babyType: 3, name: "Roxen", name2: "Roxana", nameMeaning: "Dawn", nameMeaning2: "Dawn", religion: "Zoroastrianism", twinType: "fraternal"),

    // Buddhism - Boys
    BabyNameModel(id: 361, babyType: 1, name: "Bodhi", nameMeaning: "Awakening", religion: "Buddhism"),
    BabyNameModel(id: 362, babyType: 1, name: "Dharma", nameMeaning: "Cosmic law", religion: "Buddhism"),
    BabyNameModel(id: 363, babyType: 1, name: "Karma", nameMeaning: "Action", religion: "Buddhism"),
    BabyNameModel(id: 364, babyType: 1, name: "Nirvana", nameMeaning: "Liberation", religion: "Buddhism"),
    BabyNameModel(id: 365, babyType: 1, name: "Siddhartha", nameMeaning: "Achieved", religion: "Buddhism"),
    BabyNameModel(id: 366, babyType: 1, name: "Tenzin", nameMeaning: "Holder of the teachings", religion: "Buddhism"),
    BabyNameModel(id: 367, babyType: 1, name: "Lama", nameMeaning: "Spiritual leader", religion: "Buddhism"),
    BabyNameModel(id: 368, babyType: 1, name: "Rinpoche", nameMeaning: "Precious one", religion: "Buddhism"),
    BabyNameModel(id: 369, babyType: 1, name: "Tashi", nameMeaning: "Auspicious", religion: "Buddhism"),
    BabyNameModel(id: 370, babyType: 1, name: "Kunga", nameMeaning: "All-encompassing", religion: "Buddhism"),
    BabyNameModel(id: 371, babyType: 1, name: "Dorje", nameMeaning: "Indestructible", religion: "Buddhism"),
    BabyNameModel(id: 372, babyType: 1, name: "Jigme", nameMeaning: "Fearless", religion: "Buddhism"),
    BabyNameModel(id: 373, babyType: 1, name: "Namgyal", nameMeaning: "Victorious", religion: "Buddhism"),
    BabyNameModel(id: 374, babyType: 1, name: "Pema", nameMeaning: "Lotus", religion: "Buddhism"),
    BabyNameModel(id: 375, babyType: 1, name: "Sangay", nameMeaning: "Buddha", religion: "Buddhism"),

    // Buddhism - Girls
    BabyNameModel(id: 376, babyType: 2, name: "Ananda", nameMeaning: "Bliss", religion: "Buddhism"),
    BabyNameModel(id: 377, babyType: 2, name: "Bodhi", nameMeaning: "Awakening", religion: "Buddhism"),
    BabyNameModel(id: 378, babyType: 2, name: "Choden", nameMeaning: "Devotee", religion: "Buddhism"),
    BabyNameModel(id: 379, babyType: 2, name: "Dawa", nameMeaning: "Moon", religion: "Buddhism"),
    BabyNameModel(id: 380, babyType: 2, name: "Karma", nameMeaning: "Action", religion: "Buddhism"),
    BabyNameModel(id: 381, babyType: 2, name: "Lhamo", nameMeaning: "Goddess", religion: "Buddhism"),
    BabyNameModel(id: 382, babyType: 2, name: "Norbu", nameMeaning: "Jewel", religion: "Buddhism"),
    BabyNameModel(id: 383, babyType: 2, name: "Pema", nameMeaning: "Lotus", religion: "Buddhism"),
    BabyNameModel(id: 384, babyType: 2, name: "Rinchen", nameMeaning: "Precious", religion: "Buddhism"),
    BabyNameModel(id: 385, babyType: 2, name: "Sangay", nameMeaning: "Buddha", religion: "Buddhism"),
    BabyNameModel(id: 386, babyType: 2, name: "Tenzin", nameMeaning: "Holder of the teachings", religion: "Buddhism"),
    BabyNameModel(id: 387, babyType: 2, name: "Tsomo", nameMeaning: "Goddess", religion: "Buddhism"),
    BabyNameModel(id: 388, babyType: 2, name: "Yangchen", nameMeaning: "Melodious", religion: "Buddhism"),
    BabyNameModel(id: 389, babyType: 2, name: "Zangmo", nameMeaning: "Beautiful", religion: "Buddhism"),
    BabyNameModel(id: 390, babyType: 2, name: "Dolma", nameMeaning: "Goddess Tara", religion: "Buddhism"),

    // Buddhism - Twins
    BabyNameModel(id: 391, babyType: 3, name: "Bodhi", name2: "Ananda", nameMeaning: "Awakening", nameMeaning2: "Bliss", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 392, babyType: 3, name: "Dharma", name2: "Dawa", nameMeaning: "Cosmic law", nameMeaning2: "Moon", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 393, babyType: 3, name: "Karma", name2: "Karma", nameMeaning: "Action", nameMeaning2: "Action", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 394, babyType: 3, name: "Nirvana", name2: "Norbu", nameMeaning: "Liberation", nameMeaning2: "Jewel", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 395, babyType: 3, name: "Siddhartha", name2: "Sangay", nameMeaning: "Achieved", nameMeaning2: "Buddha", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 396, babyType: 3, name: "Tenzin", name2: "Tenzin", nameMeaning: "Holder of the teachings", nameMeaning2: "Holder of the teachings", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 397, babyType: 3, name: "Lama", name2: "Lhamo", nameMeaning: "Spiritual leader", nameMeaning2: "Goddess", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 398, babyType: 3, name: "Rinpoche", name2: "Rinchen", nameMeaning: "Precious one", nameMeaning2: "Precious", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 399, babyType: 3, name: "Tashi", name2: "Tsomo", nameMeaning: "Auspicious", nameMeaning2: "Goddess", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 400, babyType: 3, name: "Kunga", name2: "Karma", nameMeaning: "All-encompassing", nameMeaning2: "Action", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 401, babyType: 3, name: "Dorje", name2: "Dolma", nameMeaning: "Indestructible", nameMeaning2: "Goddess Tara", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 402, babyType: 3, name: "Jigme", name2: "Jigme", nameMeaning: "Fearless", nameMeaning2: "Fearless", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 403, babyType: 3, name: "Namgyal", name2: "Norbu", nameMeaning: "Victorious", nameMeaning2: "Jewel", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 404, babyType: 3, name: "Pema", name2: "Pema", nameMeaning: "Lotus", nameMeaning2: "Lotus", religion: "Buddhism", twinType: "fraternal"),
    BabyNameModel(id: 405, babyType: 3, name: "Sangay", name2: "Sangay", nameMeaning: "Buddha", nameMeaning2: "Buddha", religion: "Buddhism", twinType: "fraternal"),

    BabyNameModel(id: 406, babyType: 1, name: "Simeon", nameMeaning: "Hearing and Listening", religion: "Christianity"),
    BabyNameModel(id: 407, babyType: 2, name: "Swathi", nameMeaning: "Goddess Tara", religion: "Hinduism"),
    BabyNameModel(id: 408, babyType: 1, name: "Jeevanandham", nameMeaning: "Happiest living being", religion: "Hinduism"),
    BabyNameModel(id: 409, babyType: 2, name: "Nishandhini", nameMeaning: "Goddess of the night", religion: "Hinduism"),
    BabyNameModel(id: 410, babyType: 1, name: "Vibin", nameMeaning: "Joyful and Happy", religion: "Buddhism"),


    BabyNameModel(id: 411, babyType: 1, name: "Joe", nameMeaning: "God will increase. Hebrew name: 'Yosef' ", religion: "Christianity"),
    BabyNameModel(id: 412, babyType: 1, name: "Isaac", nameMeaning: "He will rejoice. Hebrew name: 'Yitzhak'", religion: "Christianity"),
    BabyNameModel(id: 413, babyType: 2, name: "Usha", nameMeaning: "Dawn or first light.  Bringing Light.'", religion: "Christianity"),
    BabyNameModel(id: 414, babyType: 2, name: "Jane", nameMeaning: "God is gracious. Hebrew name: 'Yochanan'", religion: "Christianity"),

  ];
}